import React from 'react';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import './aurora-gradient-design-style.css';

const anatomy=[['01','COLOUR','Hues merge instead of stopping at an edge.'],['02','LIGHT','Brightness gathers, thins out and breathes.'],['03','DIFFUSION','Softness turns separate colours into atmosphere.'],['04','DEPTH','Layers create the feeling of space behind the screen.'],['05','MOTION','Slow drift makes the field continuously alive.']];

function AuroraField({variant=''}){return <div className={`aurora-field ${variant}`} aria-hidden="true"><div className="aurora-sky"/><div className="aurora-haze haze-a"/><div className="aurora-haze haze-b"/><div className="aurora-haze haze-c"/><div className="aurora-curtain curtain-a"/><div className="aurora-curtain curtain-b"/><div className="aurora-curtain curtain-c"/><div className="aurora-curtain curtain-d"/><div className="aurora-glow glow-a"/><div className="aurora-glow glow-b"/><div className="aurora-stars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="aurora-film"/></div>}

export default function AuroraGradientDesignStyle({onNavigate}){return <main className="aurora-page">
<header className="aurora-nav"><button onClick={()=>onNavigate?.('library')}><ArrowLeft size={16}/> DESIGN LIBRARY</button><button className="aurora-brand" onClick={()=>onNavigate?.('home')}><b>RYŪMA</b><em>リューマ</em></button><span>07 / AURORA</span></header>
<section className="aurora-hero"><AuroraField variant="hero-field"/><div className="hero-orbit orbit-1"/><div className="hero-orbit orbit-2"/><div className="hero-copy"><span>DESIGN ANATOMY / 07</span><h1>Aurora<br/><em>Gradient Design.</em></h1><p>Colour that doesn't sit still. Light that bends, diffuses and drifts through the interface.</p></div><div className="hero-side-note">COLOUR · LIGHT · DIFFUSION · DEPTH · MOTION</div><div className="hero-index">A / 07</div></section>
<section className="aurora-intro"><div className="section-label">THE LANGUAGE</div><div className="intro-main"><h2>A gradient can be<br/><em>a living atmosphere.</em></h2><p>Aurora Gradient Design turns colour into an environment. Instead of a fixed blend between two stops, the field behaves like light: soft at the edges, concentrated at the centre and always changing.</p></div><div className="intro-flow"><span>COLOUR</span><b>01</b><i>→</i><span>DIFFUSE</span><b>02</b><i>→</i><span>DRIFT</span><b>03</b><i>→</i><strong>FEEL</strong></div></section>
<section className="aurora-anatomy"><div className="section-label">DESIGN ANATOMY</div><div className="anatomy-heading"><h2>Not decoration.<br/><em>Behaviour.</em></h2><p>The character comes from how light moves through colour — not from adding more objects to the canvas.</p></div><div className="anatomy-grid">{anatomy.map(([n,t,c],i)=><article key={n}><div className={`mini-field mini-${i}`}><span/></div><small>{n}</small><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="aurora-showcase"><div className="showcase-copy"><span>01 / LIVING COLOUR</span><h2>Let colour<br/><em>flow into itself.</em></h2><p>There is no visible beginning or end. One hue can appear from the dark, swell into a luminous body and dissolve into another.</p><div className="spectrum"><i/><i/><i/><i/><i/></div></div><div className="showcase-field"><AuroraField variant="wide-field"/><div className="field-caption"><span>ATMOSPHERE / 01</span><b>CONTINUOUS TRANSITION</b></div></div></section>
<section className="aurora-depth"><div className="depth-field"><AuroraField variant="depth-field"/><div className="depth-label">02 / DEPTH</div><div className="depth-word">LIGHT<br/><em>HAS SPACE.</em></div></div><div className="depth-copy"><span>02 / DEPTH + DIFFUSION</span><h2>Make the screen<br/><em>feel deeper.</em></h2><p>Layer broad translucent fields instead of stacking obvious shapes. Distant colour should soften into the background while closer light carries more energy.</p><div className="depth-steps"><b>01</b><span>background haze</span><b>02</b><span>luminous layer</span><b>03</b><span>foreground glow</span></div></div></section>
<section className="aurora-motion"><div className="motion-head"><span>03 / MOTION</span><h2>Slow enough<br/><em>to feel alive.</em></h2><p>Aurora movement should be discovered rather than announced. Forms drift, stretch, overlap and return with no obvious loop.</p></div><div className="motion-stage"><AuroraField variant="motion-field"/><div className="motion-line line-a"/><div className="motion-line line-b"/><div className="motion-meta"><span>DRIFT</span><span>MORPH</span><span>DISSOLVE</span><span>RETURN</span></div></div></section>
<section className="aurora-principles"><article><span>KEEP</span><h2>Alive.</h2><p>Broad fields. Soft transitions. Uneven light. Slow movement. Darkness between colours.</p></article><article><span>AVOID</span><h2>Noise.</h2><p>Hard ribbons, obvious blobs, aggressive animation and glow that competes with the content.</p></article></section>
<section className="aurora-use"><div className="section-label">WHERE IT WORKS</div><h2>When the interface needs<br/><em>an atmosphere.</em></h2><div className="use-grid"><div><b>01</b><strong>Digital products</strong><span>Immersive landing pages and expressive product surfaces.</span></div><div><b>02</b><strong>Creative identity</strong><span>Portfolios, studios, campaigns and visual systems.</span></div><div><b>03</b><strong>Music + culture</strong><span>Posters, releases and experiences built around mood.</span></div><div><b>04</b><strong>Emerging tech</strong><span>AI, spatial interfaces and futuristic environments.</span></div></div></section>
<section className="aurora-closing"><AuroraField variant="closing-field"/><div className="closing-copy"><span>RYŪMA / DESIGN ANATOMY</span><h2>Don't paint the light.<br/><em>Design how it moves.</em></h2><button onClick={()=>onNavigate?.('library')}>BACK TO LIBRARY <ArrowUpRight size={17}/></button></div></section>
<footer className="aurora-footer"><span>RYŪMA / AURORA GRADIENT DESIGN</span><span>LIVING LIGHT · CONTINUOUS TRANSITION</span></footer>
</main>}
