import React from "react";
import "./brutalism.css";

export default function Brutalism({ onBack }) {
  const parts = [
    ["01", "TYPOGRAPHY", "Large, heavy typography becomes part of the interface itself. Type becomes a visual object, not just supporting content."],
    ["02", "CONTRAST", "Strong differences in size, weight, colour and scale create immediate visual hierarchy."],
    ["03", "STRUCTURE", "Grids, borders, columns and divisions can remain visible. The construction becomes part of the composition."],
    ["04", "RAW FORM", "Simple rectangles, lines, blocks and basic shapes replace unnecessary decoration."],
    ["05", "IMPERFECTION", "Asymmetry, unusual spacing and unexpected alignment can create personality and visual tension."]
  ];
  return <main className="brutalism-page">
    <header className="brutal-header"><button className="brutal-back" onClick={onBack}>← BACK TO LIBRARY</button></header>
    <section className="brutal-hero"><p className="brutal-eyebrow">04 · DESIGN STYLE</p><h1><span>Brutalism.</span><br/>Raw structure.<br/>Bold expression.</h1><p className="brutal-lead">Brutalism embraces strong visual decisions instead of trying to make everything polished or subtle. Heavy typography, hard edges, exposed structure and unexpected composition create an interface that feels direct, experimental and unapologetic.</p><blockquote>The design doesn't hide its structure.<br/><strong>The structure becomes the design.</strong></blockquote><div className="brutal-demo"><b>BRUTAL / 04</b><strong>MAKE<br/>IT<br/>VISIBLE.</strong><span>TYPE · GRID · CONTRAST · RAW FORM</span></div></section>
    <section className="brutal-section"><div className="brutal-heading"><span>01</span><h2>THE PARTS OF BRUTALISM</h2></div><div className="brutal-parts">{parts.map(([n,t,d]) => <article key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
    <section className="brutal-section"><div className="brutal-heading"><span>02</span><h2>THE BRUTALIST TOOLKIT</h2></div><div className="toolkit-grid"><article><b>HEAVY TYPE</b><p>Typography carries much of the visual identity.</p></article><article><b>HARD EDGES</b><p>Sharp borders and rectangular forms create a direct physical feeling.</p></article><article><b>LOUD COLOUR</b><p>Colour can be intentionally aggressive instead of restrained.</p></article><article><b>VISIBLE GRID</b><p>The underlying structure becomes part of the visual composition.</p></article><article><b>RAW IMAGERY</b><p>Images can feel cropped, rough or deliberately unconventional.</p></article></div></section>
    <section className="brutal-section"><div className="brutal-heading"><span>03</span><h2>CONTRAST</h2></div><p className="brutal-intro">Brutalism depends heavily on contrast. The difference should create intention, not random noise.</p><div className="contrast-row"><article><b>LOW</b><span>QUIET</span></article><article><b>BALANCED</b><span>CLEAR</span></article><article><b>HIGH</b><span>LOUD</span></article></div></section>
    <section className="brutal-section"><div className="brutal-heading"><span>04</span><h2>COMPOSITION</h2></div><div className="composition-grid"><article><b>ASYMMETRY</b><p>Elements don't always need to sit perfectly in the centre.</p></article><article><b>OVERLAP</b><p>Objects can cross boundaries and interact with neighbouring elements.</p></article><article><b>SCALE</b><p>A tiny element can sit beside something enormous to create tension.</p></article><article><b>INTERRUPTION</b><p>The expected visual rhythm can deliberately be broken.</p></article></div></section>
    <section className="brutal-section two-col"><div><div className="brutal-heading"><span>05</span><h2>WHERE IT WORKS</h2></div><ul><li>Creative portfolios</li><li>Editorial websites</li><li>Art and culture</li><li>Experimental products</li><li>Fashion and campaigns</li><li>Music websites</li><li>Youth-focused brands</li></ul></div><div><div className="brutal-heading"><span>06</span><h2>WHERE IT STRUGGLES</h2></div><ul><li>Complex enterprise dashboards</li><li>Dense information systems</li><li>Accessibility-critical interfaces</li><li>Interfaces requiring very predictable interaction</li><li>Products where experimentation can interfere with usability</li></ul></div></section>
    <section className="brutal-section"><div className="brutal-heading"><span>07</span><h2>BRUTALISM vs BAD DESIGN</h2></div><div className="versus"><article><h3>GOOD BRUTALISM</h3><p>Intentional contrast · deliberate asymmetry · clear hierarchy · controlled visual tension</p></article><article><h3>BAD DESIGN</h3><p>Inconsistent spacing · accidental hierarchy · unreadable text · random decoration</p></article></div><p className="intent-note">The difference is <strong>intent.</strong></p></section>
    <section className="brutal-takeaway"><span>FINAL TAKEAWAY</span><h2>MAKE THE STRUCTURE VISIBLE.</h2><p>Brutalism teaches that an interface doesn't always need to be soft, polished or invisible. It can be direct, loud, raw and experimental — but every aggressive choice should still have a reason.</p><strong>RAW DOESN'T MEAN CARELESS.</strong></section>
  </main>;
}