import React from 'react';
import { ArrowLeft, ArrowUpRight, Check, ChevronRight, CircleAlert, Command, Moon, Sparkles } from 'lucide-react';
import './dark-ui-style.css';

const anatomy=[
  ['01','SURFACE','Layers of near-black, charcoal and tinted neutrals create depth without noise.'],
  ['02','CONTRAST','The strongest contrast belongs to the information that matters most.'],
  ['03','TYPE','Weight, size and brightness determine what gets read first.'],
  ['04','ACCENT','Saturated colour becomes a signal for action, state and focus.'],
  ['05','LIGHT','Glow and highlights create atmosphere when restraint keeps them useful.']
];

const states=[['DEFAULT','Quiet. Stable. Waiting.'],['HOVER','A small shift in light or surface.'],['ACTIVE','Clear visual confirmation.'],['FOCUS','A visible invitation to interact.'],['DISABLED','Present — but deliberately quiet.']];

export default function DarkUIStyle({onNavigate}){return <main className="dark-page">
<header className="dark-nav"><button onClick={()=>onNavigate?.('library')}><ArrowLeft size={16}/> DESIGN LIBRARY</button><button className="dark-brand" onClick={()=>onNavigate?.('home')}><b>RYŪMA</b><em>リューマ</em></button><span>06 / DARK UI</span></header>
<section className="dark-hero"><div className="dark-grid"/><div className="dark-orb orb-a"/><div className="dark-orb orb-b"/><div className="hero-scan"/><div className="dark-hero-copy"><span>DESIGN ANATOMY / 06</span><h1>Design<br/><em>in the dark.</em></h1><p>Dark interfaces aren't simply black versions of light interfaces. They are systems built around contrast, hierarchy, atmosphere and controlled light.</p><button onClick={()=>document.getElementById('dark-anatomy')?.scrollIntoView({behavior:'smooth'})}>EXPLORE THE SYSTEM <ArrowUpRight size={16}/></button></div><div className="hero-console"><div className="console-top"><span>DISPLAY / 06</span><b>LIVE</b></div><div className="console-bars"><i/><i/><i/><i/><i/></div><div className="console-readout"><span>ATTENTION</span><strong>CONTROLLED</strong></div></div></section>
<section className="dark-intro"><div className="dark-label">01 / WHAT IS DARK UI?</div><div className="intro-layout"><div><h2>When the interface<br/><em>becomes a space.</em></h2></div><div><p>Dark UI uses deep surfaces, restrained contrast and luminous accents to create interfaces that feel focused, immersive and intentional.</p><p className="intro-punch">The challenge is not making things dark.<br/><strong>The challenge is deciding what deserves to be seen.</strong></p></div></div></section>
<section className="dark-anatomy" id="dark-anatomy"><div className="dark-label">02 / THE ANATOMY</div><div className="section-heading"><h2>Five decisions<br/><em>shape the darkness.</em></h2><p>Darkness becomes a design system when every visual decision has a job.</p></div><div className="anatomy-grid">{anatomy.map(([n,t,c],i)=><article key={n}><div className={`anatomy-sample sample-${i}`}><span>{n}</span>{i===0&&<><i/><b/><em/></>}{i===1&&<div className="contrast-demo"><small>SECONDARY</small><strong>PRIMARY</strong><b>FOCUS</b></div>}{i===2&&<div className="type-demo"><b>Aa</b><span>TYPE / 48</span></div>}{i===3&&<div className="accent-demo"><i/><i/><i/></div>}{i===4&&<div className="light-demo"><i/><b/></div>}</div><small>{n}</small><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="surface-section"><div className="surface-visual"><div className="surface-card back"><span>SURFACE / 01</span></div><div className="surface-card mid"><span>ELEVATED / 02</span></div><div className="surface-card front"><span>ACTIVE / 03</span><b>Darkness needs layers.</b><i><Check size={13}/> Connected</i></div></div><div className="surface-copy"><span>03 / SURFACE SYSTEM</span><h2>Darkness<br/><em>needs layers.</em></h2><p>A good Dark UI rarely uses one flat black. It builds a quiet stack: <strong>background → surface → elevated → active.</strong></p><div className="surface-rule"><b>01</b><span>BACKGROUND</span><b>02</b><span>SURFACE</span><b>03</b><span>ELEVATED</span><b>04</b><span>ACTIVE</span></div></div></section>
<section className="contrast-section"><div className="contrast-copy"><span>04 / CONTRAST</span><h2>Make the important<br/><em>things brighter.</em></h2><p>Primary content gets clarity. Secondary content steps back. Inactive elements become quieter. Important actions receive the strongest visual signal.</p><strong>Contrast is hierarchy made visible.</strong></div><div className="contrast-stack"><div><small>TERTIARY</small><span>Metadata and supporting information</span></div><div><small>SECONDARY</small><span>Supporting interface content</span></div><div className="contrast-primary"><small>PRIMARY</small><span>Important information</span><b>Focus</b></div></div></section>
<section className="accent-section"><div className="accent-field"><div className="accent-glow"/><span>ACCENT / SIGNAL</span><strong>01</strong><div className="signal-dot"/></div><div className="accent-copy"><span>05 / ACCENT COLOUR</span><h2>A little colour<br/><em>goes a long way.</em></h2><p>On a dark canvas, saturated colour becomes powerful. A single accent can communicate action, success, warning, error and focus.</p><div className="signal-list"><span><i/>ACTION</span><span><i/>SUCCESS</span><span><i/>WARNING</span><span><i/>ERROR</span></div></div></section>
<section className="type-section"><div className="type-header"><span>06 / TYPOGRAPHY</span><h2>Type becomes <em>light.</em></h2><p>In Dark UI, white isn't always white. Brightness itself becomes a typographic hierarchy.</p></div><div className="type-specimen"><div className="type-primary"><small>PRIMARY</small><strong>Design systems</strong><span>100% brightness · highest attention</span></div><div className="type-secondary"><small>SECONDARY</small><strong>Supporting information</strong><span>68% brightness · readable, quieter</span></div><div className="type-meta"><small>META</small><strong>03 / DARK UI</strong><span>42% brightness · almost disappears</span></div></div></section>
<section className="states-section"><div className="dark-label">07 / COMPONENT STATES</div><div className="section-heading"><h2>Interfaces are<br/><em>never static.</em></h2><p>A Dark UI becomes expressive through states—not decoration.</p></div><div className="state-list">{states.map(([name,desc],i)=><div className={`state-row state-${i}`} key={name}><b>0{i+1}</b><strong>{name}</strong><span>{desc}</span><ChevronRight size={16}/></div>)}</div></section>
<section className="light-section"><div className="light-visual"><div className="light-halo"/><div className="light-core"><Sparkles size={22}/></div><span>FOCUS</span></div><div className="light-copy"><span>08 / LIGHT + DEPTH</span><h2>Light is a<br/><em>structural tool.</em></h2><p>Glow shouldn't exist just because glow looks cool. It can establish hierarchy, focus, elevation, interaction and atmosphere.</p><strong>Light tells the eye where to go.</strong></div></section>
<section className="works-section"><div className="dark-label">09 / WHERE IT WORKS</div><h2>Darkness <em>has a purpose.</em></h2><div className="works-grid"><article><Command/><b>CREATIVE TOOLS</b><p>Keep the interface quiet while the work takes centre stage.</p></article><article><span className="code-symbol">&lt;/&gt;</span><b>DEVELOPER TOOLS</b><p>Reduce visual noise around dense information.</p></article><article><Moon/><b>MEDIA + CULTURE</b><p>Create an immersive environment around content.</p></article><article><CircleAlert/><b>AI PRODUCTS</b><p>Build focused environments for interaction and generated content.</p></article></div></section>
<section className="principles-section"><div className="principle-head"><span>10 / THE PRINCIPLES</span><h2>Design less.<br/><em>Signal more.</em></h2></div><div className="principles"><div><b>01</b><strong>Don't make everything black.</strong><span>Darkness needs structure.</span></div><div><b>02</b><strong>Don't make everything bright.</strong><span>Contrast loses meaning when everything competes.</span></div><div><b>03</b><strong>Use colour with intention.</strong><span>Accent colour should communicate, not decorate.</span></div><div><b>04</b><strong>Let surfaces create depth.</strong><span>Small differences can establish an entire spatial system.</span></div><div><b>05</b><strong>Design the states.</strong><span>A Dark UI is alive through interaction.</span></div></div></section>
<section className="dark-closing"><div className="closing-noise"/><div className="closing-copy"><span>RYŪMA / DESIGN ANATOMY</span><h2>Dark isn't the<br/>absence of <em>colour.</em></h2><p>It's the controlled use of light, contrast, surface and attention.</p><strong>When everything is quiet, the smallest signal can become the strongest one.</strong><button onClick={()=>onNavigate?.('library')}>BACK TO LIBRARY <ArrowUpRight size={16}/></button></div></section>
<footer className="dark-footer"><span>RYŪMA / DARK UI</span><span>SURFACE · CONTRAST · LIGHT · FOCUS</span></footer>
</main>}
