import React, { useEffect } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import './glassmorphism-style.css';
import './glassmorphism-background.css';

const layers=[
 {no:'01',title:'Transparency',copy:'A translucent white surface lets the colour and light beneath remain part of the composition.'},
 {no:'02',title:'Depth',copy:'Layered surfaces, soft shadows and overlapping edges create a clear sense of front and back.'},
 {no:'03',title:'Light',copy:'Soft highlights and blurred colour fields make the material feel luminous rather than heavy.'},
 {no:'04',title:'Hierarchy',copy:'Opacity, scale and position separate primary content from supporting details.'},
];

export default function GlassmorphismStyle({onNavigate}){useEffect(()=>{document.body.classList.add('glass-route-body');return()=>document.body.classList.remove('glass-route-body')},[]);return <main className="glass-style-page">
 <div className="glass-blob blob-red"/><div className="glass-blob blob-purple"/><div className="glass-blob blob-pink"/><div className="glass-dot-grid"/>
 <header className="glass-style-nav"><button onClick={()=>onNavigate?.('library')}><ArrowLeft size={15}/> DESIGN LIBRARY</button><div><b>RYUMA</b><span>リューマ</span></div><span>DESIGN LANGUAGE / 02</span></header>
 <section className="glass-hero"><div className="glass-intro"><span>02 / GLASSMORPHISM</span><h1>Light<br/><em>through glass.</em></h1><p className="glass-lead">A visual language built from transparency, soft light and layered depth.</p><p>The surface stays light and restrained while colour, blur and edges create the sense of a material floating above the background.</p><div className="glass-palette"><i/><i/><i/><i/><i/></div></div>
  <div className="glass-specimen"><div className="glass-reflection"/><div className="glass-card main"><span>RYŪMA / STUDY 02</span><h2>Clarity<br/><em>in layers.</em></h2><p>White glass · soft light · subtle depth</p><button>EXPLORE <ArrowRight size={15}/></button></div><div className="glass-card mini mini-one"><small>01</small><strong>TRANSPARENCY</strong><span>LET LIGHT THROUGH</span></div><div className="glass-card mini mini-two"><small>02</small><strong>DEPTH</strong><span>BUILD WITH LAYERS</span></div></div></section>
 <section className="glass-section"><div className="glass-label"><span>03</span><b>DESIGN ANATOMY</b></div><div><h2>Five parts.<br/><em>One glass language.</em></h2><div className="glass-parts"><article><b>COLOUR</b><h3>Soft atmosphere</h3><p>White remains dominant while pale red and purple provide the energy behind the surface.</p></article><article><b>TYPE</b><h3>Dark contrast</h3><p>Black and deep purple carry information; light red and pink provide emphasis.</p></article><article><b>FORM</b><h3>Rounded surfaces</h3><p>Quiet curves and thin borders make the glass feel physical without becoming heavy.</p></article><article><b>SPACE</b><h3>Breathing room</h3><p>Generous margins let the translucent layers remain visually distinct.</p></article><article><b>MOTION</b><h3>Gentle response</h3><p>Small shifts, reveals and hover movement should feel soft and weightless.</p></article></div></div></section>
 <section className="glass-section glass-composition"><div className="glass-label"><span>04</span><b>COMPOSITION</b></div><div><h2>Make the surface<br/><em>stand out.</em></h2><div className="glass-demo"><div className="demo-ring ring-red"/><div className="demo-ring ring-purple"/><div className="glass-card demo-card"><span>GLASS / 01</span><strong>Foreground<br/><em>over atmosphere.</em></strong><small>THE BACKGROUND IS PART OF THE MATERIAL.</small></div><div className="demo-orb red"/><div className="demo-orb purple"/></div></div></section>
 <section className="glass-section"><div className="glass-label"><span>05</span><b>THE LAYERS</b></div><div><h2>What makes it<br/><em>feel like glass?</em></h2><div className="glass-layer-list">{layers.map(item=><article key={item.no}><span>{item.no}</span><div><h3>{item.title}</h3><p>{item.copy}</p></div></article>)}</div></div></section>
 <footer className="glass-footer"><span>GLASSMORPHISM / 02</span><h2>Light surface.<br/><em>Clear hierarchy.</em></h2><p>A focused design specimen for studying transparency, depth and light — not a replacement for the Ryūma site environment.</p><button onClick={()=>onNavigate?.('library')}>BACK TO DESIGN LIBRARY <ArrowLeft size={15}/></button></footer>
 </main>}
