import "./design-system.css";
import React, { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowRight, Compass, Eye, Lightbulb, Search, ArrowLeft, X } from "lucide-react";
const Minimalism = lazy(() => import("./Minimalism.jsx"));
const Glassmorphism = lazy(() => import("./Glassmorphism.jsx"));
const Neumorphism = lazy(() => import("./Neumorphism.jsx"));
const Brutalism = lazy(() => import("./Brutalism.jsx"));
import BrutalSecondary from "./BrutalSecondary.jsx";
const Skeuomorphism = lazy(() => import("./Skeuomorphism.jsx"));
const Claymorphism = lazy(() => import("./Claymorphism.jsx"));
const Maximalism = lazy(() => import("./Maximalism.jsx"));
const MaterialDesign = lazy(() => import("./MaterialDesign.jsx"));
const FlatDesign = lazy(() => import("./FlatDesign.jsx"));
const AuroraGradient = lazy(() => import("./AuroraGradient.jsx"));
const DarkUIDesign = lazy(() => import("./DarkUIDesign.jsx"));
import "./style.css";
import "./enhancements.css";
import "./typography.css";
import "./spacing.css";
import "./light-material.css";
import "./contrast.css";
import "./start-here.css";
import "./library.css";
import "./material-design.css";
import "./material-preview.css";
import "./dark-ui-design.css";
import "./home-live-preview-fix.css";
import "./minimal-preview.css";
import "./minimalism-geometric.css";
import "./flat-preview-fix.css";
import "./maximalism-live-override.css";
import "./home-viewport.css";
import "./heading-overrides.css";
import "./style-loader.css";

