import React from "react";
import "./maximalism.css";

export default function Maximalism({ onBack }) {
  const parts = [["01","ABUNDANCE","Multiple visual elements work together instead of relying on one dominant element."],["02","LAYERING","Images, typography, shapes, patterns and surfaces overlap to create depth and complexity."],["03","COLOUR","Bold or contrasting colour combinations create energy and visual personality."],["04","TYPOGRAPHY","Multiple type sizes, weights and styles can coexist to create hierarchy and expression."],["05","PATTERN & TEXTURE","Patterns, illustrations and textures add visual richness and prevent large areas from feeling empty."],["06","VISUAL DENSITY","The interface intentionally contains more information and decoration within a given space."]];
  const toolkit = [["COLOUR","Bold palettes, unexpected combinations and strong accents."],["TYPOGRAPHY","Large type, contrasting weights and multiple typographic treatments."],["PATTERNS","Repeating shapes, illustrations and decorative motifs."],["IMAGERY","Photography, illustrations, graphics and visual references can coexist."],["LAYERS","Elements overlap rather than remaining isolated."],["DECORATION","Borders, ornaments, textures and details become part of the composition."]];
  return <main className="max-page">
    <header className="max-header"><button onClick={onBack}>← BACK TO LIBRARY</button><span>01.07 / LISM FAMILY</span></header>
    <section className="max-hero">
      <div className="max-kicker">01.07 · VISUAL STYLE / MAXIMALISM</div>
      <div className="max-hero-grid">
        <div className="max-hero-copy"><h1><span>MAXI</span>MALISM</h1><h2>MORE IS<br/><em>MORE.</em></h2><p className="lead">Maximalism embraces abundance. Colour, typography, imagery, pattern, texture and decoration are deliberately layered into a visual language that feels expressive, energetic and unmistakably alive.</p><div className="max-tags"><b>TYPE</b><b>COLOUR</b><b>IMAGE</b><b>PATTERN</b><b>LAYER</b></div></div>
        <div className="max-collage" aria-label="Maximalist visual composition"><span className="collage-grid"/><span className="collage-circle circle-one"/><span className="collage-circle circle-two"/><span className="collage-star">✦</span><span className="collage-ring"/><b className="collage-word word-max">MAX</b><b className="collage-word word-more">MORE</b><span className="collage-vertical">VISUAL / ENERGY / EXPRESSION</span><span className="collage-note">EDITORIAL<br/>DESIGN STUDY<br/>01 / 07</span><span className="collage-scribble">/////</span><div className="collage-panel">BE BOLD.<br/>BE BUSY.<br/><strong>BE CLEAR.</strong></div></div>
      </div>
      <blockquote>More isn't the goal.<br/><strong>Meaningful more is.</strong></blockquote>
    </section>
    <section className="max-principle"><span>THE PRINCIPLE</span><h2>SIMPLE IDEA.<br/><strong>LOUD EXECUTION.</strong></h2><p>Maximalism is not random clutter. The composition can be dense, but hierarchy still decides where the eye lands first.</p></section>
    <section className="max-section"><div className="max-heading"><span>01</span><h2>THE PARTS OF MAXIMALISM</h2></div><div className="max-parts">{parts.map(([n,t,d])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
    <section className="max-section max-section-dark"><div className="max-heading"><span>02</span><h2>THE MAXIMALIST TOOLKIT</h2></div><div className="toolkit">{toolkit.map(([t,d])=><article key={t}><b>{t}</b><p>{d}</p></article>)}</div></section>
    <section className="max-section"><div className="max-heading"><span>03</span><h2>CONTROLLED CHAOS</h2></div><p className="section-copy">Maximalism can look chaotic, but <strong>good maximalism is designed chaos.</strong> The elements may be abundant, but they still need relationships.</p><div className="chaos-flow"><div>ABUNDANCE</div><span>→</span><div>LAYERING</div><span>→</span><div>HIERARCHY</div><span>→</span><strong>CONTROLLED CHAOS</strong></div><p className="section-copy">The designer decides what the eye notices first, second and third.</p></section>
    <section className="max-section"><div className="max-heading"><span>04</span><h2>WHY IT WORKS</h2></div><div className="why-grid"><div className="max-number">✦</div><div><h3>VISUAL PERSONALITY</h3><p>Maximalism can create strong visual personality, emotional energy, memorable experiences, rich storytelling and a sense of individuality.</p><p>It can communicate a brand's personality much more aggressively than a restrained visual language.</p></div></div></section>
    <section className="max-section two-col"><div><div className="max-heading"><span>05</span><h2>WHERE IT WORKS</h2></div><ul><li>Entertainment websites</li><li>Fashion and lifestyle brands</li><li>Music and culture</li><li>Editorial experiences</li><li>Portfolios</li><li>Campaign pages</li><li>Creative agencies</li><li>Youth-oriented products</li></ul></div><div><div className="max-heading"><span>06</span><h2>WHERE IT STRUGGLES</h2></div><p className="section-copy">Maximalism becomes problematic when <strong>everything demands attention at once.</strong></p><ul><li>Poor readability</li><li>Visual fatigue</li><li>Weak hierarchy</li><li>Slower scanning</li><li>Confusing navigation</li><li>Overwhelming interfaces</li></ul><p className="warning">More elements don't automatically mean more communication.</p></div></section>
    <section className="max-section"><div className="max-heading"><span>07</span><h2>MAXIMALISM vs MINIMALISM</h2></div><div className="versus"><article><small>MAXIMALISM</small><h3>Abundance</h3><p>Layering · Expression · Visual richness</p></article><article><small>MINIMALISM</small><h3>Reduction</h3><p>Space · Restraint · Visual clarity</p></article></div><p className="choice">Neither is automatically better. <strong>The question is what the experience needs.</strong></p></section>
    <section className="max-takeaway"><span>FINAL TAKEAWAY</span><h2>MAKE MORE<br/>MEAN MORE.</h2><p>Maximalism isn't simply putting everything on the screen. It's about <strong>using abundance intentionally.</strong></p><p>When colour, type, imagery, pattern and texture have a relationship, complexity becomes character.</p><b>GOOD MAXIMALISM ISN'T NOISE.<br/>IT'S ORGANISED ABUNDANCE.</b></section>
  </main>;
}
